image: node:8

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:vulnerabilities:
  script:
    - npm run vuln-test

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run generate
