image: node:8

before_script:
  - npm install
  - apt-get update -qq && apt-get install -y -qq sshpass

cache:
  paths:
    - node_modules/

publish:
  environment: Staging
  only:
    - dev
  script:
    - npm run generate
    - cd _dist/
    - ls
